name: HEAVY!!!
run-name: ${{ github.actor }} runs HEAVY tests via GitHub Actions1 🚀
on:
  merge_group:
jobs:
  HEAVY_TEST_JOB:
    runs-on: ubuntu-latest
    steps:
      - run: echo "BEFORE THE SLEEP"
      - run: sleep 30
      - run: echo "After the sleep!"
