name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  merge_group:
    types: [checks_requested]
jobs:
  HEAVY_TEST_JOB:
    runs-on: ubuntu-latest
    steps:
      - run: echo "BEFORE THE SLEEP"
      - run: sleep 30
      - run: echo "After the sleep!"
